[package]
name = "fe"
version = "1.0.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.1"
ndarray = "0.15.6"
rand = "0.8.5"
rug = "1.19.0"
rayon= "1.7.0"
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
env_logger = "0.11.3"
